from dataclasses import dataclass


@dataclass(frozen=True)
class GeneratedVideo:
    """
    Represents a video generated by an animation provider.
    """

    path: str
    width: int
    height: int
    fps: int
    frame_count: int
    provider: str

    @property
    def duration(self) -> float:
        """
        Return video duration in seconds.
        """
        return self.frame_count / self.fps