from pydantic import BaseModel, Field


class GeneratedImage(BaseModel):
    """
    Represents an image generated by an image provider.
    """

    path: str = Field(
        min_length=1,
        description="Path of the generated image",
    )

    width: int = Field(
        gt=0,
        description="Generated image width",
    )

    height: int = Field(
        gt=0,
        description="Generated image height",
    )

    format: str = Field(
        min_length=1,
        description="Generated image format",
    )

    provider: str = Field(
        min_length=1,
        description="Provider used to generate the image",
    )